### ISSUE TITLE
Error with context

### ISSUE THREAD

**Issue by iRayzer** [apollographql/meteor-integration#101]
Hello,
I have this error on every request when the user is not authenticated...

[Meteor Apollo Integration] Something bad happened when handling a request on the GraphQL server. Your GraphQL server is not working as expected: [ReferenceError: context is not defined]

What can I do about it ?

**Comment by iRayzer** [comment]
I found that I'm supposed to do this to ensure that context is defined : 

createApolloServer({
  schema,
  context: {},
});

But it doesn't change a thing... :(

**Comment by xavcz** [comment]
Thanks @iRayzer for opening an issue! 👍 

Which version of `meteor/apollo` do you use? v0.9.0? That may be related to [this line](https://github.com/apollographql/meteor-integration/blob/master/src/main-server.js#L172).

Let me publish a patch.

**Comment by carlosbergfeld** [comment]
And out of curiosity, tests don't catch that because `context` is a [global variable in Mocha's BDD interface](https://mochajs.org/#bdd).

**Comment by iRayzer** [comment]
Yes I'm on 0.9.0 :)

Thanks for your help!

**Comment by xavcz** [comment]
0.9.1 published! It should be better @iRayzer!

@carlosbergfeld yeah just noticed that! I was wtf the `context` is 😨 : 
```
{ [Function] skip: [Function], only: [Function] }
```

**Comment by iRayzer** [comment]
Yes it works! 
Thanks a lot!
