### ISSUE TITLE
interfaceToUse is not a function

### ISSUE THREAD

**Issue by rkstar** [apollographql/meteor-integration#107]
i'm using the apollo package (1.0.0) in my meteor `1.5.2.1` app and getting an error which seems like it's pretty straightforward.  is this working for anyone else?

[this line](https://github.com/apollographql/meteor-integration/blob/master/src/main-client.js#L52) is causing problems with my project

here is the error:
```
Uncaught TypeError: interfaceToUse is not a function
    at createMeteorNetworkInterface (main-client.js:52)
    at index.js (index.js:14)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at main.js (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at app.js?hash=479d09f06da60d18f342bb00611f84ba55450a22:390
createMeteorNetworkInterface @ main-client.js:52
index.js @ index.js:14
fileEvaluate @ modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343
require @ modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238
main.js @ main.js:1
fileEvaluate @ modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343
require @ modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238
(anonymous) @ app.js?hash=479d09f06da60d18f342bb00611f84ba55450a22:390
```

**Comment by lorensr** [comment]
Hi, what version of `apollo-client` are you on, and what's your code at `index.js:14`? Thanks!

**Comment by rkstar** [comment]
thanks for the speedy response @lorensr !  i beat my head against this for a while and it came down to simple sleep deprivation and a missed name on my part. 👎 

i was using `<ApolloClient client={client}>` instead of `<ApolloProvider client={client}>` in my code.  sorry for wasting your time too!  closing... 🔐

**Comment by maka-io** [comment]
I'm getting this same error: "TypeError: interfaceToUse is not a function. (In 'interfaceToUse(interfaceArgument)', 'interfaceToUse' is undefined)" and I am using ApolloProvider.

apollo-client 2.0.1

```
import { Meteor } from 'meteor/meteor';

import ApolloClient from 'apollo-client';
import { meteorClientConfig } from 'meteor/apollo';
import { ApolloProvider } from 'react-apollo';

const client = new ApolloClient(meteorClientConfig());
```

**Comment by lorensr** [comment]
This package doesn't support 2.0 yet—should work with 1.*

**Comment by maka-io** [comment]
Thank you @lorensr.  Is that 1.* of apollo-client, react-apollo, or both?
