### ISSUE TITLE
Warn about possibly-incompatible npm peer deps

### ISSUE THREAD

**Issue by lorensr** [apollographql/meteor-integration#108]
See: https://github.com/apollographql/meteor-integration/issues/96#issuecomment-300984908

**Comment by xavcz** [comment]
Yeah! 

Considering how Apollo Client is evolving, I've been thinking recently that this package should now only export a link to configure the context client-side (auth token stored in local storage) and a function to verify the authentication server-side.

So this package only export something Meteor specific and we let people write their own client / server. What do you think?

**Comment by lorensr** [comment]
I like exporting & documenting both of those, but if there's a good set of defaults that most people would like, I'd like to provide in addition a fewer-LOC interface similar to current API.
