### ISSUE TITLE
Help with Schema must be an instance of GraphQLSchema error

### ISSUE THREAD

**Issue by townmulti** [apollographql/meteor-integration#110]
My meteor app was working fine until I updated the npm modules, now I'm getting this error:

`W20171027-07:32:09.755(-5)? (STDERR) Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
W20171027-07:32:09.757(-5)? (STDERR)     at invariant (/home/buck4/myapp/node_modules/apollo-server-express/node_modules/apollo-server-core/node_modules/graphql/jsutils/invariant.js:18:11)
W20171027-07:32:09.759(-5)? (STDERR)     at Object.validate (/home/buck4/myapp/node_modules/apollo-server-express/node_modules/apollo-server-core/node_modules/graphql/validation/validate.js:59:72)
W20171027-07:32:09.760(-5)? (STDERR)     at doRunQuery (/home/buck4/myapp/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runQuery.js:88:38)
W20171027-07:32:09.761(-5)? (STDERR)     at /home/buck4/myapp/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runQuery.js:22:54
W20171027-07:32:09.763(-5)? (STDERR)     at /home/buck4/.meteor/packages/promise/.0.9.0.179ibqp++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:39`

I have searched and tried many solutions with no resolve.

I ran `npm list | grep graphql` and got

![image](https://user-images.githubusercontent.com/10806345/32104377-c8bd431c-bae9-11e7-87b2-7003b26342be.png)

I ran `find node_modules -name graphql` and got

![image](https://user-images.githubusercontent.com/10806345/32104395-da53c01a-bae9-11e7-86a5-748982990d9c.png)

Does anyone have any suggestions?

**Comment by lorensr** [comment]
Try these versions of Apollo client and server:
https://github.com/apollographql/meteor-integration/blob/master/package.json
https://github.com/apollographql/meteor-integration/blob/master/package.json

**Comment by townmulti** [comment]
Thanks @lorensr for your help.
I ended up downloading my app build from Galaxy and using the node_modules from it. So I will work from there on my apollo graphql updates.
