### ISSUE TITLE
Allow custom token header by removing hard coded "meteor-login-token"

### ISSUE THREAD

**Issue by j0nd0n7** [apollographql/meteor-integration#120]
When a graphql api is used by 3rd party apps  it is required for them to provide the meteor-login-token which doesn't look so standard.

It would be nice to have a configuration option to provide a way to use `Authorization: Bearer <token>`

**Comment by lorensr** [comment]
Thanks for the suggestion—this is now possible in v3.0. Docs for the new API: https://www.apollographql.com/docs/react/recipes/meteor.html
