### ISSUE TITLE
Align to be closer with Apollo Boost

### ISSUE THREAD

**Issue by toinevk** [apollographql/meteor-integration#121]
Apollo Boost provides a good zero-config way to start using Apollo Client with some decent defaults. This fits well with Meteor's overall story - would you be open to a PR that extends the current meteor client to include apollo boost default (i.e. Error Handling)?

**Comment by lorensr** [comment]
v3.0 has been released with a new API, and you can use `apollo-boost` directly: https://www.apollographql.com/docs/react/recipes/meteor.html
