### ISSUE TITLE
Support for Apollo Client 2.0?

### ISSUE THREAD

**Issue by aadamsx** [apollographql/meteor-integration#125]
Hi, the link on this repot takes us to the Apollo Client docs, where the heading Integrating with Meteor, states the dos are for Apollo Client 1.0.  

My question, does this integration lib support/use the Apollo Client 2.0 lib?

Also, will the Apollo Client integration with Meteor documents ever be updated for Apollo Client 2.0?

**Comment by aadamsx** [comment]
After reviewing the PRs, it seems this is Apollo Client 2.0 Meteor integration.  Is there some examples on how to use this integration or what it actually does?

**Comment by lorensr** [comment]
Hey, sorry—theres a PR open with the docs update. For now, you can view it here:

https://github.com/apollographql/apollo-client/blob/lorensr/update-meteor-docs/docs/source/recipes/meteor.md

Supports latest client and server, and the code is mainly just auth
