### ISSUE TITLE
Error: Could not get   https://warehouse.meteor.com

### ISSUE THREAD

**Issue by Ethaan** [apollographql/meteor-integration#132]
**Labels**

- [x] has-reproduction
- [x] blocking

By running `meteor add apollo` from a fresh clone, i'm getting.

```
Error: Could not get 

https://warehouse.meteor.com/builds/pokpfhHYNwcMvbkee/1539412416684/Ja7NCzX7ZW/apollo-

3.0.1-os+web.browser+web.browser.legacy+web.cordova.tgz; server returned [502]
```

**Comment by lorensr** [comment]
From a fresh clone of which repo?

**Comment by Ethaan** [comment]
Sorry a new app created from `meteor create`, i got that error for some hours, then it works, could be my internet?, closing this
