### ISSUE TITLE
TypeError: createMeteorNetworkInterface is not a function

### ISSUE THREAD

**Issue by maka-io** [apollographql/meteor-integration#133]
Using meteor Apollo v3.0.1, fresh install, getting the following error with implementation:

![screen shot 2018-11-21 at 1 37 37 pm](https://user-images.githubusercontent.com/3743882/48861866-a25fde00-ed92-11e8-95b1-50702773226e.png)

![screen shot 2018-11-21 at 1 38 06 pm](https://user-images.githubusercontent.com/3743882/48861894-b60b4480-ed92-11e8-962b-a6c3106cda31.png)

**Comment by lorensr** [comment]
The API changed with v3: 

https://www.apollographql.com/docs/react/recipes/meteor.html#Usage

**Comment by maka-io** [comment]
ETA on doc update for SSR example?

**Comment by lorensr** [comment]
Whenever someone contributes a PR for it!

#126
