### ISSUE TITLE
External .graphql files

### ISSUE THREAD

**Issue by townmulti** [apollographql/meteor-integration#42]
Can someone give a snippet example of how to store the graphql queries externally or separately in a file (.graphql or whatever extension)? And from which directory to import them into the meteor app?

**Comment by stubailo** [comment]
Why do this rather than put them as strings in the code?

**Comment by townmulti** [comment]
Sorry just back from vacation! Now trying to recapture the thought process :) ...it seems that I have a lot of duplicated code when I do graphql unions. As in the fields to retrieve from the query, I have to go thru several files to update these. I think that fragments will help, but haven't quite found a good example of how to use them. In one context, it seems that fragments denote queries to pre-fetch. And in another context, it seems that fragments are used to help limit duplicated code. I guess waiting for Meteor 1.5 and its suggested use of fragments will help. 

Also, I saw some conversation about .graphql filles somewhere and was wondering how to use them.

**Comment by stubailo** [comment]
There are docs about fragments here btw: http://dev.apollodata.com/react/fragments.html

**Comment by townmulti** [comment]
Okay thanks! Gonna close this.

**Comment by jamiter** [comment]
Some tools detect those schema files to give you autocomplete etc. without running a server. So I'm still interested in this.

**Comment by xavcz** [comment]
Maybe you can do something like this? https://github.com/tmeasday/create-graphql-server/blob/0cc74ecd2f9a9581c861321de4822e5151836e95/test/output-app/schema/index.js#L1-L6

**Comment by lorensr** [comment]
Could also try a build plugin
https://docs.meteor.com/api/packagejs.html#build-plugin-api

**Comment by jamiter** [comment]
@lorensr, I hoped there would already be one ;) I'll give it a shot in the coming future. Thanks!

**Comment by lorensr** [comment]
Nice, would be cool!

**Comment by xavcz** [comment]
Holy moly that looks great!! Keep us posted here or on Slack @jamiter 🙏

**Comment by jamiter** [comment]
So v1 would simply allow this:

```js
import schema from './schema.graphql';

console.log(schema); // Schema string
```

Any other extensions that should be supported? Maybe `.gql`. Not sure what the standards are at the moment.

**Comment by jamiter** [comment]
I present to you a first working version:

https://github.com/Swydo/meteor-graphql

See it in action in this [demo](https://blaze-apollo-example.swydo.com/) ([code](https://github.com/Swydo/blaze-apollo-example))

Feedback welcome!

**Comment by stubailo** [comment]
@jamiter that's awesome! And looks like it will support the `#import` stuff from the webpack loader out of the box as well!

**Comment by jamiter** [comment]
Yeah it's using that exact loader underwater. No need to reinvent the wheel 😄

**Comment by csillag** [comment]
So v1 would simply allow this:

import schema from './schema.graphql';
console.log(schema); // Schema string

Any other extensions that should be supported?


How about .graphqls?

I have seen that around for schemes.
(As opposed to .graphql, which is often used for queries.)

**Comment by jamiter** [comment]
@csillag, I mostly saw IDE support for `.gql` and `.graphql`. Could you show me an example of where `.graphqls` is used? 2 options is already 1 to many in my opinion 😆

**Comment by gergely-ujvari** [comment]
A [JS GraphQL plugin for Jetbrains IDE](https://plugins.jetbrains.com/plugin/8097-js-graphql) uses `.graphqls` files for the schema.  
Some screenshots on their repo page: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/

**Comment by jamiter** [comment]
@gergely-ujvari, thanks! I'll add it in the next release!

**Comment by jamiter** [comment]
Ah, why not fix it right away :wink: `.graphqls` is availble now in v0.0.2

**Comment by xavcz** [comment]
@jamiter this plugin is really awesome (with even the combination of your latest PR on `graphql-tools` 🎉)!

Do you mind doing a PR on the Meteor apollo docs to add a section about it? 🙏

**Comment by jamiter** [comment]
@xavcz, sure! Just have to find the time 😉

**Comment by jamiter** [comment]
@gergely-ujvari, the Jetbrains plugin indeed uses the `.graphqls` file format. Sadly, it doesn't recognise them for usage, only generates one from a `json` file. I can't point the plugin to a `.graphqls` file for autocompletion. That would have just been totally awesome and make the circle complete!

I opened a ticket for it: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/70

Maybe you could comment or thumbs-up over there. Thanks!
