### ISSUE TITLE
Allow using Apollo with Meteor server side only

### ISSUE THREAD

**Issue by elie222** [apollographql/meteor-integration#48]
My app is written in Blaze and I don't want to use Apollo client right now. I am interested in connecting from a React Native app to Apollo on my Meteor server however.

I removed `apollo-client` as an npm package from my Meteor app and I now get the following error warning in the browser console:
```
check-npm-versions.js:53 WARNING: npm peer requirements (for apollo) not installed:
 - apollo-client@^0.4.0 || ^0.3.0 not installed.

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
checkNpmVersions @ check-npm-versions.js:53
modules-runtime.js?hash=ab7e8d3…:470 Uncaught Error: Cannot find module 'apollo-client'(…)
```

I don't if this has any major effects, but it would be nice to be able to use Apollo with Meteor server side only.

**Comment by lorensr** [comment]
Yes, this package code could be split into two packages, `meteor/apollo-client` and `meteor/apollo-server`, and this package could just imply both of them.

**Comment by jamiter** [comment]
The server-side of this package is mostly setting up Meteor authentication for `graphql-server-express` (and GraphiQL express). If your React Native app doesn't use this type of authentication then it might be just as easy to setup the GraphQL server yourself. It's only a few lines of code:

```javascript
import { graphqlExpress, graphiqlExpress } from 'graphql-server-express';
import bodyParser from 'body-parser';
import express from 'express';

import { WebApp } from 'meteor/webapp';

const server = express();

// GraphQL endpoint
server.use('/graphql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));

// GraphiQL endpoint
server.use('/graphiql', graphiqlExpress({}));

// This binds the specified paths to the Express server running Apollo + GraphiQL
WebApp.connectHandlers.use(Meteor.bindEnvironment(graphQLServer));
```

Just a suggestion :)

**Comment by xavcz** [comment]
@jamiter 👍 

@elie222 you can use the solution proposed by @jamiter, or if you want to use `meteor/apollo` package with a React Native app, you may need to define some CORS options as the RN app will be on a different port than the Meteor app:

```js
import cors from 'cors';
import { createApolloServer } from 'meteor/apollo';

// ...

createApolloServer({
  schema,
}, {
  configServer: expressServer => expressServer.use(cors()),
});
```

And in the future we may separate it in two packages right 🤔
