### ISSUE TITLE
Log errors in development

### ISSUE THREAD

**Issue by lorensr** [apollographql/meteor-integration#49]
Maybe this?

```
if (Meteor.isDevelopment)
  serverOptions.debug = true
```

http://dev.apollodata.com/tools/graphql-server/setup.html#graphqlOptions

**Comment by lorensr** [comment]
@sachag is this what you were looking for? In 0.2.0, for example this error gets printed when you should be returning an array from a resolver, given the schema:

![image](https://cloud.githubusercontent.com/assets/251288/20019525/32482cda-a2a3-11e6-9a91-2f6adc34bce9.png)

![image](https://cloud.githubusercontent.com/assets/251288/20019527/39bbc45e-a2a3-11e6-9be9-dc178a143860.png)

**Comment by SachaG** [comment]
Oh cool!

**Comment by xavcz** [comment]
Closing, as available in the package 👍
