### ISSUE TITLE
Tracker/Blaze integration with Apollo Client

### ISSUE THREAD

**Issue by lorensr** [apollographql/meteor-integration#5]
This would go in a different package. If you're interested and would like some guidance, talk to Sashko!

**Comment by lorensr** [comment]
See also https://github.com/apollostack/docs/issues/22

**Comment by devvelopu** [comment]
Repo: https://github.com/apollostack/blaze-apollo

**Comment by lorensr** [comment]
https://github.com/apollostack/blaze-apollo

**Comment by lorensr** [comment]
https://github.com/apollostack/blaze-apollo

**Comment by jamiter** [comment]
This looks like a good issue to discuss the scope of the Meteor integration. What should this integration do? Looks like we are excluding some parts.

What it *doesn't* integrate with:
- Tracker (ReactiveDict? MiniMongo?)
- Blaze
- DDP?

What *does* it integrate with:
- It provides the userId and makes sure express works with Meteor
- What did I miss?

What features can we expect that need a Meteor integration
- I'm a bit clueless here

If it doesn't work with Tracker (and then automatically with Blaze/ReactiveDict/MiniMongo), then most of the work is already done I guess.

Just curious about any possible plans :)

**Comment by lorensr** [comment]
I'm thinking that anything that not all Meteor apps use should be a different package – at least Blaze is on that list. 

Re: tracker/minimongo, I'm guessing `meteor 1.5`, the apollo integration meteor release, will talk about when/how to use it vs redux? @tmeasday might know

> What features can we expect that need a Meteor integration

Sorry, what do you mean here? :)

**Comment by jamiter** [comment]
Sorry, that was phrased badly. ;)

What I meant was: What features can we expect in this package? The most important ones are already here. I see a ticket for subscriptions, but they kinda work out of the box, right?

> Re: tracker/minimongo, I'm guessing meteor 1.5, the apollo integration meteor release, will talk about when/how to use it vs redux?

Is this the package that will be the basis for this integration? I expected some discussion in these issues about where it is heading I guess. Or is it something MDG is talking about internally? Maybe you don't know, but I'm just very interested in the subject :)

If this is it, thats just fine of course. Just wondering if we can expect more.

**Comment by lorensr** [comment]
> but they kinda work out of the box, right?

Haven't tried em yet!

> Is this the package that will be the basis for this integration? I expected some discussion in these issues about where it is heading I guess. Or is it something MDG is talking about internally? 

Think so, and yes. Don't think it will be long before they publish their thoughts

**Comment by jamiter** [comment]
We created a Blaze integration that works with this package:

https://github.com/Swydo/blaze-apollo

It supports reactive queries, as in Tracker reactive, and automatically unsubscribes from updates when a Template is destroyed. See the Readme for more info.

Any feedback is welcome :)

**Comment by xavcz** [comment]
@jamiter yay that's awesome! 🎉 

Do you think you could do a PR [on the core-docs in the Meteor section](https://github.com/apollographql/core-docs/blob/master/source/meteor.md) to mention your package? 💯

**Comment by jamiter** [comment]
I'll give it a shot!

**Comment by stubailo** [comment]
I think that resolves this!

**Comment by xavcz** [comment]
Yep thanks! 🎉
