### ISSUE TITLE
Allow OPTION request to graphql endpoint

### ISSUE THREAD

**Issue by matteodem** [apollographql/meteor-integration#59]
see https://github.com/Akryum/vue-apollo/issues/18. Not sure if it's the apollo-client or vue package that does the request itself.

If it's easily adjustable in the meteor app itself, please guide me on how to do that.

**Comment by xavcz** [comment]
Hey @matteodem, did you succeeded in making Meteor / Vue & Apollo working together in the end?

**Comment by matteodem** [comment]
no, I've tried writing my own integration in the meteor app by re-using the code that the meteor/apollo pkg has and slightly adjusting it. Didn't solve the problem unfortunately. 

Here's a reproduction repo https://github.com/matteodem/vue-apollo-bug

**Comment by xavcz** [comment]
Made a PR on your repo, it's working! 😄 

I'll update the Meteor Apollo docs about this nitty gritty `configServer` option!

**Comment by matteodem** [comment]
thanks so much!

**Comment by xavcz** [comment]
Closing as fixed 👍
