### ISSUE TITLE
userId caching

### ISSUE THREAD

**Issue by lorensr** [apollographql/meteor-integration#6]
I was planning on only using `lru-cache`, but @stubailo reminded me with talk of `observe` that we're in Meteorland, not just nodeland. Shouldn't we first check whether Meteor has the current user's login info? If the client has a DDP connection open to the same app server as the app server that the GraphQL request comes to (which should happen if you have sticky routing like Galaxy), the info should be in memory in the same node process, right? Is there a Meteor lookup table of `connection/session id -> connection object`? In which case we could use the `userId` on the `connection` object. So the client would send two headers, one with `Meteor.connection._lastSessionId`, and one with the login token. It would try to look up the session, and if fails, use the `lru-cache`.

**Comment by jamiter** [comment]
@lorensr, I think my DDP suggestion would fix this, right? If we simply use DDP for retrieving the data, then we have the userId if a user is logged in.

https://github.com/apollostack/meteor-integration/issues/39

**Comment by lorensr** [comment]
Yep!

**Comment by lorensr** [comment]
Let's just use #4
