### ISSUE TITLE
Update to latest apollo-client version

### ISSUE THREAD

**Issue by jschlieber** [apollographql/meteor-integration#66]
First of all: thanks for providing this integration for Meteor.

When using the latest meteor-integration from Atmosphere I get the warning: `apollo-client@0.8.2 installed, apollo-client@^0.5.0 needed`. Can that be safely ignored? 

If not, am I constrained to `v0.5.0` of apollo-client with Meteor (at least when I want to use this integration)? When will there be an update that supports the latest versions?

Thank you so much for your efforts!

**Update** (Just for the sake of completeness)

I get the following warnings on the server side:

```
WARNING: npm peer requirements (for apollo) not installed:
 graphql-server-express@0.6.0 installed, graphql-server-express@^0.4.3 needed
 graphql@0.9.1 installed, graphql@^0.7.0 || ^0.8.0 needed
 graphql-tools@0.10.0 installed, graphql-tools@^0.8.0 needed
```

**Comment by xavcz** [comment]
Hey @jschlieber!

No bother, you can use the latest Apollo & friends packages 👍 

The warning you get is from, we'll update in the following days https://github.com/apollographql/meteor-integration/blob/master/check-npm.js

**Comment by jschlieber** [comment]
@xavcz

Okay, great. Yes, saw that. Thank you!

**Comment by xavcz** [comment]
Closing, we are allowing multiple versions so you don't have to bother if you are using the latest or previous ones 😌

**Comment by lorensr** [comment]
Thanks for the issue, client `v0.8.*` came in `meteor/apollo@0.3.1` and the rest came in `v0.4.0`
