### ISSUE TITLE
Demystifying Meteor ↔️ Apollo integration with a code tour

### ISSUE THREAD

**Issue by xavcz** [apollographql/meteor-integration#72]
Current state of the art
---
We have docs, we have starter kit, but I feel like many folks in the Meteor world still seem to have troubles to grasp how it works together.

I'm not that much on the forums, but I've seen that in my local meetup (Paris, FR) & listening to Transmission Podcast.

What if we take people by the hand
---
I've created a [code tour](https://www.codetours.xyz) to demystify that: 

[![Some gif to show how to take the codetour, just click on it](https://d3uepj124s5rcx.cloudfront.net/items/1N1C3L0S0K1l23360j1R/Screen%20Recording%202017-02-14%20at%2012.20%20PM.gif?v=2dbfcb55)](https://www.codetours.xyz/tour/xavcz/meteor-apollo-codetour)

Here is how to have a look at it directly: https://www.codetours.xyz/tour/xavcz/meteor-apollo-codetour

To this repo watchers, contributors & anyone interested in
---
I would love your feedback on it to make it clearer how to spread the word that building something with Meteor & Apollo is not obscure at all!
➡️ Codetour: https://www.codetours.xyz/tour/xavcz/meteor-apollo-codetour
➡️ Repo to correct my fragile English syntax and enhance the Markdown formatting: https://github.com/xavcz/meteor-apollo-codetour 😄

**Comment by stubailo** [comment]
Wow!! This is incredible!

This might be the first code tour ever made by people who didn't work on codetours :]
