### ISSUE TITLE
Remove isomorphic-fetch from prod?

### ISSUE THREAD

**Issue by lorensr** [apollographql/meteor-integration#77]
can `isomorphic-fetch` be removed from these?

https://github.com/apollographql/meteor-integration/blob/e840181985787950235ad29317631b6304e7515a/main-client.js#L2

https://github.com/apollographql/meteor-integration/blob/e4dbf57692e2f62b801de428342a08b0d27b188b/check-npm.js#L7

https://github.com/apollographql/core-docs/blob/master/source/meteor.md

and just add the package for testing?

**Comment by xavcz** [comment]
Sure, it can! 👌  This removal should come with the removal of `Headers` (used in [accounts middleware](https://github.com/apollographql/meteor-integration/blob/master/main-client.js#L81)).

We can use a normal object instead and not even need to depends on fetch (deps handled by `apollo-client`)
