### ISSUE TITLE
GraphiQL server broken in 0.4.0 ?

### ISSUE THREAD

**Issue by csillag** [apollographql/meteor-integration#79]
Upgrading the apollo atmosphere package to 0.4.0 has broken the Graph*i*QL server for me.
(The problem  happens without updating any of the NPM modules.)

The page loads, but no queries work.
After a long while, the timeout message says "Failed to fetch".

**Comment by xavcz** [comment]
So yeah, it's all things that were broken. 

There is now an update on GitHub, but while waiting for the package to be published to Atmosphere, you can do:

```sh
# in your app's root directory
mkdir packages # if you don't have a /packages directory
cd packages
git clone https://github.com/apollographql/meteor-integration.git
```

And it should work (I tested locally on the starter kit)

**Comment by csillag** [comment]
> [...] while waiting for the package to be published to Atmosphere [...]

What is the typical time required to publish a new version?

**Comment by xavcz** [comment]
As soon as someone with the right to push it up is available 😌

**Comment by xavcz** [comment]
`0.4.1` is on Atmosphere, issue fixed! Thanks for reporting folks!
