### ISSUE TITLE
0.4.0 Broken all GraphQL queries

### ISSUE THREAD

**Issue by Siyfion** [apollographql/meteor-integration#81]
Dang, I have no idea what's going on, but upgrading to `0.4.0` shows no server errors, but all my clients are now completely unable to call any queries, mutations, etc.

Something is very, very broken.

**Comment by csillag** [comment]
This might be the same problem as described in #79

**Comment by timbrandin** [comment]
Duplicate yes, and all queries are broken as this issue mentions.

**Comment by xavcz** [comment]
Yep problem found, it'll be solved pretty soon 🤐 

https://github.com/apollographql/meteor-integration/pull/80#issuecomment-282732738

**Comment by xavcz** [comment]
While waiting `0.4.1` to be pushed to Atmosphere

```sh
# in your app's root directory
mkdir packages # if you don't have a /packages directory
cd packages
git clone https://github.com/apollographql/meteor-integration.git
```

And it should work (I tested locally on the starter kit)

**Comment by xavcz** [comment]
`0.4.1` is on Atmosphere, issue fixed! Thanks for reporting folks!
