### ISSUE TITLE
[0.6.0] graphql-tag warning is back

### ISSUE THREAD

**Issue by csillag** [apollographql/meteor-integration#87]
After updating the apollo package to 0.6.0, this message is back on the browser console:

```
Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.
See https://github.com/apollographql/graphql-tag/issues/54 for more information.
```

I have seen this earlier, but not with the recent versions.
A regression, maybe?

**Comment by xavcz** [comment]
What does say your package.json about Graphql related packages?

**Comment by csillag** [comment]
This:
```
    "graphql": "^0.9.1",
    "graphql-server-express": "^0.6.0",
    "graphql-tools": "^0.10.1",
```

**Comment by stubailo** [comment]
None of those use graphql-tag - how about other Apollo stuff?

**Comment by csillag** [comment]
Sorry, the Apollo packages:
```
    "apollo-client": "^1.0.0-rc.2",
    "react-apollo": "^1.0.0-rc.2",
    "apollo-codegen": "github:csillag/apollo-codegen#11dbf9c3e731da7919d6f5c7134f1d0cfa8d5af3",
```

**Comment by xavcz** [comment]
Almost in in the list 😛 (just kidding). It comes from `subscriptions-transport-ws`: https://github.com/apollographql/subscriptions-transport-ws/blob/e6a12d8813a95ebd7fb674b1b46180b3d87deb08/src/helpers.ts#L2

Opened a PR on the repo to use `print` directly from `graphql`. Meanwhile, this warning is harmless and we'll be careful of updating dependencies of `meteor/apollo` as soon as things change 👍  

Thanks for the care again @csillag 🚀
