### ISSUE TITLE
createApolloServer throws error when customOptions is a function

### ISSUE THREAD

**Issue by carlosbergfeld** [apollographql/meteor-integration#90]
The `createApolloServer` function stopped working when `customOptions` is a function. It depends on a variable that is out of scope. I believe it was introduced after the changes for subscriptions in https://github.com/apollographql/meteor-integration/commit/c506c5e273269b0ba375894554709a9f9d0a1141#diff-102002bcf9b709c35ef841116ac3fb43R77.

This is important to set up context variables that depend on the request object, like setting up Optics as shown in http://dev.apollodata.com/core/meteor.html#Apollo-Optics.

**Comment by xavcz** [comment]
Yay, thanks @carlosbergfeld! 

We hit this bug yesterday with @Siyfion, it'll be fixed asap.

**Comment by xavcz** [comment]
Fixed in 0.7.0 👌
