### ISSUE TITLE
Store updates fail after upgrading to 1.0.0

### ISSUE THREAD

**Issue by helfer** [apollographql/meteor-integration#94]
See issue here: https://github.com/apollographql/apollo-client/issues/1524

@Siyfion is using meteor-integration. It broke going from rc.6 to rc.7 or 1.0.0.

**Comment by xavcz** [comment]
Thanks @helfer, I'm having a look 👌

**Comment by xavcz** [comment]
Fixed by https://github.com/apollographql/apollo-client/pull/1540 🎉
