### ISSUE TITLE
Out of sync with NPM versions again...

### ISSUE THREAD

**Issue by csillag** [apollographql/meteor-integration#96]
```
WARNING: npm peer requirements (for apollo) not installed:
 - graphql-server-express@0.7.2 installed, graphql-server-express@^0.6.0 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
```

**Comment by xavcz** [comment]
Instead of annoying warnings throw by the meteor npm requirements package for being too much up-to-date, I'm thinking that a "crash feature" if you don't have the package installed would be great?

Something that doesn't check package versions but rather check if they exist (can be required) and crash with an explicit error telling which packages are missing?

Would you be OK for a PR on that? 😊

**Comment by jshimko** [comment]
Yes please!  Seriously, anything but that awful version checker package.  I am SO sick of the excessive console warnings from that.  Tons of Meteor packages use that and it feels like pointless warning come up every other week.  Honestly, I'd rather just have my build fail from a missing dependency than have to look at that message over and over for a version mismatch that isn't actually a problem.

Ok, mini rant over.  :)

**Comment by xavcz** [comment]
So anyone wanna tackle this issue over the weekend with a PR ? 💯

**Comment by csillag** [comment]
> So anyone wanna tackle this issue over the weekend with a PR ?

If there are no takers, how about just updating the referenced version numbers, for now?

**Comment by xavcz** [comment]
@csillag please open a PR for the version numbers meanwhile and ping me, I'll merge it and publish the package right away. I'll see what I can do in the following days for "fail early" and now more warnings.

**Comment by xavcz** [comment]
Ok, removed the check completely.

**Comment by lorensr** [comment]
it's important to let people know what versions of peer deps we're compatible with. perhaps in the case in which the installed dep is newer, we can say "might be incompatible" instead of just "incompatible"
