### ISSUE TITLE
Insecure request to /graphql

### ISSUE THREAD

**Issue by calvintychan** [apollographql/meteor-integration#98]
Hi – I am using the createApolloServer in meteor and I have everything working as expected in local development. However, when I deployed my application to meteor galaxy. I am seeing an issue with the `/graphql` request if I am loading my app in HTTPS. 

Here is the error:
```Mixed Content: The page at 'https://nls-tesla-stage.meteorapp.com/login' was loaded over HTTPS, but requested an insecure resource 'http://nls-tesla-stage.meteorapp.com/graphql'. This request has been blocked; the content must be served over HTTPS.```

Can I configure to always use HTTPS when sending a request to the Apollo server?

**Comment by lorensr** [comment]
Weird, if you're using latest, it uses `Meteor.absoluteUrl`, which should match HTTPS, but you can override the `uri`:

http://dev.apollodata.com/core/meteor.html#createMeteorNetworkInterface

**Comment by calvintychan** [comment]
Weird. I type `Meteor.absoluteUrl('graphql');` in the browser but it is always returning `http` instead of `https`. Maybe the method absoluteUrl is not doing what it is supposed to be doing?  I am going to override the uri and see if it works. Thanks!

**Comment by lorensr** [comment]
`Meteor.absoluteUrl` gives `https` on my app and Galaxy. Looking at the docs, is your `ROOT_URL` http? 

https://docs.meteor.com/api/core.html#Meteor-absoluteUrl

**Comment by xavcz** [comment]
@calvintychan did configuring `ROOT_URL` solved your problem?

**Comment by calvintychan** [comment]
Setting the Meteor.absoluteUrl explicitly resolve my problem. However, @lorensr, did you have to configure your `ROOT_URL` in your galaxy app?  If so, how do you do it?

**Comment by xavcz** [comment]
Awesome!

You can do it via your `settings.json` file: http://galaxy-guide.meteor.com/environment-variables.html 💯
